### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by jordandekraker** [Bradley-Karat/Hippo_Spin_Testing#1]
Hey @Bradley-Karat, I had an issue with my install that is easily fixed by removing this line: https://github.com/Bradley-Karat/Hippo_Spin_Testing/blob/4ae4f709941ff0e3489e6a56cab16d755c5d4946/setup.py#L39C17-L39C17

Just thought you might want to be aware!

**Comment by Bradley-Karat** [comment]
Ah thanks for pointing this out, now fixed!
